"""Paid, fictional-bank example blueprint — the marketplace's premium/publisher-branded tier.

"Maple Trust Financial" is an invented demo publisher, not a real institution. This blueprint
exists to demonstrate what a bank's advisory team would actually ship: more scenarios, richer
framing, still 100% grounded in the client's own pre-computed figures (the bank never sees the
client's raw data — only the blueprint's logic/assumptions run on the client's own machine).
"""
from __future__ import annotations

import json
from typing import Any

from localagents.agents import register
from localagents.harness import Harness

DISCLAIMER = (
    "This automated stress test was generated by a local LLM using Maple Trust Financial's "
    "published assumptions, applied to your own computed figures. It is not personalized "
    "financial advice from a licensed advisor and should not be the sole basis for any "
    "financial decision."
)

SCENARIOS: dict[str, str] = {
    "rate_shock_up_2pt": "Variable interest rates rise 2 points and stay there for a year.",
    "job_loss_3mo": "Primary income drops to $0 for 3 months, then fully recovers.",
    "market_correction_20pct": "Investment/retirement balances fall 20%, recover over 18 months.",
    "inflation_spike_6pct": "Annual inflation runs at 6% for 2 years, eroding fixed budgets.",
    "income_growth_stall_2yr": "Income growth stalls at 0% for 2 years while expenses keep rising.",
}

_SPECIALIST_SYSTEM_PROMPT = (
    "You are a stress-test specialist on Maple Trust Financial's advisory desk. You only ever "
    "reason from the verified figures you are given — never invent or estimate numbers. Given "
    "one shock scenario and the client's real financial figures (net worth, liquidity, "
    "cashflow, diversification, goal feasibility, income forecast), write a short (3-4 "
    "sentence) internal note: how would this scenario affect them, and how resilient are they?"
)

_LEAD_SYSTEM_PROMPT = (
    "You are the lead advisor on Maple Trust Financial's advisory desk, presenting a stress-test "
    "review directly to your client. You have specialist notes for five shock scenarios plus "
    "the client's headline figures — all already verified, computed facts. Never invent numbers "
    "beyond what you were given. Write a clear, client-facing summary with this structure:\n"
    "1. Overall resilience readout (1-2 sentences)\n"
    "2. Scenario-by-scenario summary (most concerning first)\n"
    "3. Impact on any active financial goals\n"
    "4. 3-5 concrete next steps to improve resilience\n"
    "Keep it under 350 words and end with exactly this line: " + DISCLAIMER
)


def _facts(snapshot: dict[str, Any], *keys: str) -> str:
    return json.dumps({key: snapshot.get(key) for key in keys}, indent=2, default=str)


@register("maple_trust.advisory_stress_test")
def run(harness: Harness, snapshot: dict[str, Any] | None = None, **kwargs: Any) -> str:
    """Entry point called by the blueprint loader after entitlement (license) is verified."""
    snapshot = snapshot or {}
    facts = _facts(
        snapshot, "net_worth", "liquidity", "cashflow", "diversification", "goal_feasibility", "income_forecast"
    )

    notes = []
    for scenario_id, description in SCENARIOS.items():
        specialist = harness.build_agent(system_prompt=_SPECIALIST_SYSTEM_PROMPT)
        note = specialist(f"Scenario: {description}\n\nClient's verified data:\n{facts}")
        notes.append(f"[{scenario_id}] {description}\n{note}")

    lead_input = f"Headline figures:\n{facts}\n\n" + "\n\n".join(notes)
    lead_agent = harness.build_agent(system_prompt=_LEAD_SYSTEM_PROMPT)
    return str(lead_agent(lead_input))
