"""Free, in-house stress-test blueprint: a per-scenario specialist reviews one plausible shock
against the user's already-computed wealth snapshot, then a lead-summary agent synthesizes an
overall resilience readout. Same never-invent-numbers grounding pattern as
`localagents.agents.wealth_advisor` — every specialist is handed pre-computed facts only.
"""
from __future__ import annotations

import json
from typing import Any

from localagents.agents import register
from localagents.harness import Harness

DISCLAIMER = (
    "This is an automated, informational stress test generated by a local LLM from your own "
    "computed figures — it is not personalized financial advice and should not be the sole "
    "basis for any financial decision."
)

SCENARIOS: dict[str, str] = {
    "rate_shock_up_2pt": (
        "Variable interest rates (mortgage, lines of credit) rise by 2 percentage points and "
        "stay there for at least a year."
    ),
    "job_loss_3mo": (
        "The client's primary income drops to $0 for 3 months, then fully recovers."
    ),
    "market_correction_20pct": (
        "Investment/retirement account balances fall 20% and take 18 months to recover."
    ),
}

_SPECIALIST_SYSTEM_PROMPT = (
    "You are a stress-test specialist at a financial advisory firm. You only ever reason from "
    "the verified figures you are given — never invent or estimate numbers. Given one specific "
    "shock scenario and the client's real liquidity/cashflow/net-worth/diversification figures, "
    "write a short (3-4 sentence) internal note: how would this scenario actually affect them, "
    "and how resilient are they to it?"
)

_LEAD_SYSTEM_PROMPT = (
    "You are the lead advisor presenting stress-test results directly to your client. You have "
    "specialist notes for several shock scenarios plus their headline net-worth/liquidity "
    "figures — all already verified, computed facts. Never invent numbers beyond what you were "
    "given. Write a clear, client-facing summary with this structure:\n"
    "1. Overall resilience readout (1-2 sentences)\n"
    "2. Scenario-by-scenario summary (most concerning first)\n"
    "3. 2-4 concrete next steps to improve resilience\n"
    "Keep it concise (under 300 words) and end with exactly this line: " + DISCLAIMER
)


def _facts(snapshot: dict[str, Any], *keys: str) -> str:
    return json.dumps({key: snapshot.get(key) for key in keys}, indent=2, default=str)


@register("loonie.core_stress_test")
def run(harness: Harness, snapshot: dict[str, Any] | None = None, **kwargs: Any) -> str:
    """Entry point called by the blueprint loader: `harness` builds specialist/lead agents,
    `snapshot` is the caller's already-computed wealth analytics summary (see
    `localagents.agents.wealth_advisor.LifeosClient` for how to fetch one from Loonie)."""
    snapshot = snapshot or {}
    facts = _facts(snapshot, "net_worth", "liquidity", "cashflow", "diversification")

    notes = []
    for scenario_id, description in SCENARIOS.items():
        specialist = harness.build_agent(system_prompt=_SPECIALIST_SYSTEM_PROMPT)
        note = specialist(f"Scenario: {description}\n\nClient's verified data:\n{facts}")
        notes.append(f"[{scenario_id}] {description}\n{note}")

    lead_input = f"Headline figures:\n{facts}\n\n" + "\n\n".join(notes)
    lead_agent = harness.build_agent(system_prompt=_LEAD_SYSTEM_PROMPT)
    return str(lead_agent(lead_input))
