"""A real-world LocalAgents use case: an orchestrated, multi-specialist wealth-advisory review.

Mirrors how a real wealth advisory firm runs a client review — a few narrow specialists each
look at one slice of the client's real (already-computed) financial data, then a lead advisor
synthesizes their notes into one prioritized, client-facing recommendation. Every specialist is
grounded in pre-computed statistics only (Loonie's own analytics engine, not raw transactions) —
the model is never shown raw data rows and never asked to compute a number itself.

The registered preset's callable shape is `(harness, snapshot) -> str` (not `(harness) -> Agent`
like the docstring example in `localagents.agents`) — presets can be any callable shape a given
use case needs; the registry itself doesn't enforce one.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

import httpx

from localagents.agents import register
from localagents.harness import Harness

DISCLAIMER = (
    "This is an automated, informational review generated by a local LLM — it is not "
    "personalized financial advice from a licensed advisor and should not be the sole basis for "
    "any financial decision."
)


@dataclass
class LifeosClient:
    """Thin client for Loonie's (lifeos) FastAPI backend — the real source of a user's wealth
    data for this example. Point `fetch_wealth_snapshot` at any other app exposing similar
    computed analytics to reuse this same advisor with a different data source."""

    base_url: str
    token: str

    @classmethod
    def login(cls, base_url: str, email: str, password: str, timeout: float = 30) -> LifeosClient:
        response = httpx.post(f"{base_url}/auth/login", json={"email": email, "password": password}, timeout=timeout)
        response.raise_for_status()
        return cls(base_url=base_url, token=response.json()["access_token"])

    def fetch_wealth_snapshot(self, timeout: float = 30) -> dict[str, Any]:
        response = httpx.get(
            f"{self.base_url}/wealth/analytics/summary",
            headers={"Authorization": f"Bearer {self.token}"},
            timeout=timeout,
        )
        response.raise_for_status()
        return response.json()


def _facts(snapshot: dict[str, Any], *keys: str) -> str:
    """Formats a subset of the already-computed analytics snapshot as JSON for a specialist
    prompt — keeps each specialist's context narrow and on-topic."""
    return json.dumps({key: snapshot.get(key) for key in keys}, indent=2, default=str)


_CASHFLOW_SYSTEM_PROMPT = (
    "You are a cash-flow and budgeting specialist at a wealth advisory firm. You only ever "
    "reason from the verified figures given to you — never invent or estimate numbers. Read the "
    "client's liquidity, cashflow, and budget data and write a short (3-5 sentence) internal note "
    "for the lead advisor: is the client's spending healthy, is there a liquidity cushion, and are "
    "any budgets trending over? Be specific with the numbers you were given."
)

_RISK_SYSTEM_PROMPT = (
    "You are a risk and diversification specialist at a wealth advisory firm. You only ever "
    "reason from the verified figures given to you — never invent or estimate numbers. Read the "
    "client's net worth, diversification, and asset-performance data and write a short (3-5 "
    "sentence) internal note for the lead advisor: is the client over-concentrated in any one "
    "bucket, and how are their held/sold assets performing?"
)

_GOALS_SYSTEM_PROMPT = (
    "You are a goals and retirement-planning specialist at a wealth advisory firm. You only ever "
    "reason from the verified figures given to you — never invent or estimate numbers. Read the "
    "client's goal-feasibility and income-forecast data and write a short (3-5 sentence) internal "
    "note for the lead advisor: which goals are on/off track, and does the income trend support "
    "them?"
)

_LEAD_ADVISOR_SYSTEM_PROMPT = (
    "You are the lead relationship advisor at a boutique wealth advisory firm, presenting a "
    "quarterly review directly to your client. You have three specialist notes (cash flow, "
    "risk & diversification, goals) plus the client's headline net-worth figures — all already "
    "verified, computed facts. Never invent numbers beyond what you were given. Write a warm, "
    "clear, client-facing review with this structure:\n"
    "1. Where you stand today (2-3 sentences, headline numbers)\n"
    "2. What's working well\n"
    "3. What needs attention (prioritized, most important first)\n"
    "4. 2-4 concrete, specific next steps\n"
    "Keep it concise (under 300 words) and end with exactly this line: " + DISCLAIMER
)


def _run_specialist(harness: Harness, system_prompt: str, facts: str) -> str:
    agent = harness.build_agent(system_prompt=system_prompt)
    result = agent(f"Here is the client's verified data:\n{facts}")
    return str(result)


@register("wealth_advisor")
def run_wealth_advisor_review(harness: Harness, snapshot: dict[str, Any]) -> str:
    """Orchestrates a 3-specialist + 1-lead-advisor review over a real (already-computed) wealth
    analytics snapshot. Returns the lead advisor's final client-facing text."""
    cashflow_note = _run_specialist(
        harness, _CASHFLOW_SYSTEM_PROMPT, _facts(snapshot, "liquidity", "cashflow", "budget_statuses")
    )
    risk_note = _run_specialist(
        harness, _RISK_SYSTEM_PROMPT, _facts(snapshot, "net_worth", "diversification", "asset_performance")
    )
    goals_note = _run_specialist(
        harness, _GOALS_SYSTEM_PROMPT, _facts(snapshot, "goal_feasibility", "income_forecast")
    )

    lead_input = (
        f"Headline figures:\n{_facts(snapshot, 'net_worth', 'liquidity')}\n\n"
        f"Cash-flow specialist note:\n{cashflow_note}\n\n"
        f"Risk specialist note:\n{risk_note}\n\n"
        f"Goals specialist note:\n{goals_note}"
    )
    lead_agent = harness.build_agent(system_prompt=_LEAD_ADVISOR_SYSTEM_PROMPT)
    return str(lead_agent(lead_input))
